services:
  edge:
    image: edge:t2
    restart: always
    build:
      context: edge
      args:  # This is where we specify the build arguments for edge service
        EDGE_BUILD_TYPE: dev  # Default value; you can override this when running `docker-compose build`
        WEBAPP_BUILD_TYPE: docker_frontm  # Default value; you can override this too
    depends_on:
      - mongo
      - redis
    networks:
      - mongo-net
      - redis-net
      - express-net
    expose:
      - 4001
    ports:
      - "4001:4001"
  
  webapp:
    image: edge:t2
    restart: always
    build:
      context: webapp
      args:  # This is where we specify the build arguments for webapp service
        EDGE_BUILD_TYPE: dev  # Default value; you can override this when running `docker-compose build`
        WEBAPP_BUILD_TYPE: docker_frontm  # Default value; you can override this too
    depends_on:
      - mongo
      - redis
      - edge
    networks:
      - mongo-net
      - redis-net
      - express-net
      - webapp-net
    expose:
      - 8080 
    ports:
      - "8080:8080"

  redis:
    image: redis:alpine
    restart: always
    expose:
      - 6379
    networks:
      - redis-net
    ports:
      - "6379:6379"

  mongo:
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    networks:
      - mongo-net
    expose:
      - 27017
    ports:
      - "27017:27017"

networks:
  mongo-net:
  redis-net:
  express-net:
  webapp-net:

