services:
  edge:
    restart: always
    build:
      context: edge
    volumes:
      - ./bots:/usr/src/bots
    depends_on:
      - mongo
      - redis
    networks:
      - mongo-net
      - redis-net
      - express-net
    expose:
      - 4001
    ports:
      - "4001:4001"
  webapp:
    build:
      context: webapp 
    depends_on:
      - mongo
      - redis
      - edge
    networks:
      - mongo-net
      - redis-net
      - express-net
      - webapp-net
    expose:
      - 8080 
    ports:
      - "8080:8080"

  redis:
    image: redis:alpine
    restart: always
    expose:
      - 6379
    networks:
      - redis-net
    ports:
      - "6379:6379"

  mongo:
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    networks:
      - mongo-net
    expose:
      - 27017
    ports:
      - "27017:27017"

networks:
  mongo-net:
  redis-net:
  express-net:
  webapp-net:

