name: OLG Build and Deploy

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Select build type'
        required: true
        type: string
      build_description:
        description: 'Description of the build'
        required: true
        type: string
      docker_tags:
        description: 'Tags for Docker images (comma-separated)'
        required: true
        type: string

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

     

      - name: Build Docker Image
        run: docker-compose -f compose.yaml build

     

      - name: Update Docker Compose file
        id: update-compose
        run: |
          # Update image tags in the Docker Compose file
          sed -i "s/image: soumyanaveen\/webapp:.*/image:  soumyanaveen\/webapp:${{ github.run_number }}/" compose.yaml
          sed -i "s/image:  soumyanaveen\/edge:.*/image:  soumyanaveen\/edge:${{ github.run_number }}/" compose.yaml
          
      - name: Push Docker Image to Docker Hub
        run: docker push soumyanaveen/olgs:tagname
        
      - name: Send email notification for deployment job
        if: success()      
        uses: dawidd6/action-send-mail@v3
        with:
         server_address: smtp.gmail.com
         server_port: 587
         username: ${{ secrets.EMAIL_USERNAME }}
         password: ${{ secrets.EMAIL_PASSWORD }}
         from: 'kamchamswarna@gmail.com'
         to: 'soumyasg12@gmail.com'
         subject: 'Deployment job completed successfully'
         body: 'The deployment job in your workflow completed successfully.
