name: Check Runner OS

on:
  push:
    branches:
      - main

jobs:
  check-runner-os:
    runs-on: ubuntu-latest
    steps:
      - name: Print OS information
        run: |
          echo "Operating System:"
          uname -a
