name: OLG Build and Deploy

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Select build type'
        required: true
        type: string
      build_description:
        description: 'Description of the build'
        required: true
        type: string
      docker_tags:
        description: 'Tags for Docker images (comma-separated)'
        required: true
        type: string

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

     

      - name: Build Docker Image
        run: docker-compose -f compose.yaml build

      - name: Tag and Push Images
        run: |
          for image in edge webapp; do
            docker tag $image:$VERSION ${{ inputs.docker_tags }}/$image:$VERSION
            docker push ${{ inputs.docker_tags }}/$image:$VERSION
          done

      - name: Generate Updated Docker Compose File
        run: |
          echo "version: '3.8'" > docker-compose.yml
          echo "services:" >> docker-compose.yml
          for service in webapp edge redis mongo; do
            image_tag=${{ inputs.docker_tags }}/$service:$VERSION
            echo "  $service:" >> docker-compose.yml
            echo "    image: $image_tag" >> docker-compose.yml
          done
