name: OLG Build and Deploy

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Select build type'
        required: true
        type: string
      build_description:
        description: 'Description of the build'
        required: true
        type: string
      docker_tags:
        description: 'Tags for Docker images (comma-separated)'
        required: true
        type: string

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

     

      - name: Build Docker Image
        run: docker-compose -f compose.yaml build

      - name: Tag and Push Images
        run: |
          IFS=',' read -ra tags_array <<< "${{ inputs.docker_tags }}"
          for tag in "${tags_array[@]}"; do
            docker tag edge:latest ${{ secrets.DOCKERHUB_USERNAME }}/edge:$tag
            docker tag webapp:latest ${{ secrets.DOCKERHUB_USERNAME }}/webapp:$tag
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/edge:$tag
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/webapp:$tag
          done

      - name: Generate Updated Docker Compose File
        run: |
          echo "version: '3.8'" > docker-compose.yml
          echo "services:" >> docker-compose.yml
          for service in webapp edge redis mongo; do
            image_tag=${{ inputs.docker_tags }}/$service:$VERSION
            echo "  $service:" >> docker-compose.yml
            echo "    image: $image_tag" >> docker-compose.yml
          done
      - name: Send mail
        if: always()
        uses: dawidd6/action-send-mail@v2
        with:
          # mail server settings
          server_address: smtp.gmail.com
          server_port: 465
         # user credentials
          username: ${{ secrets.EMAIL_USERNAME }}
          password: sona2626@
         # email subject
          subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
         # email body as text
          body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
         # comma-separated string, send email to
          to: soumyasg12@gmail.com
         # from email name
          from: soumya
