name: OLG Application Pipeline

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Select build type'
        required: true
        default: 'dev_olg'
        options:
          - value: 'dev_frontm'
            description: 'Development build for Frontm'
          - value: 'dev_olg'
            description: 'Development build for OLG'
          - value: 'prod_frontm'
            description: 'Production build for Frontm'
          - value: 'prod_olg'
            description: 'Production build for OLG'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
        run: docker-compose -f compose.yaml build

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: soumyanaveen
          password: dckr_pat_4UltzycL8wDzvR347q0w7eT1aco

      - name: Extract Image Name
        id: extract_image_name
        run: |
         IMAGE_NAME=$(docker-compose -f compose.yaml config | grep 'image:' | awk '{print $2}')
         echo "::set-output name=image_name::$IMAGE_NAME"

      - name: Tag Docker Image
        run: |
          docker tag ${{ steps.extract_image_name.outputs.image_name }} soumyanaveen/olg:tagname

      - name: Push Docker Image to Docker Hub
        run: docker push soumyanaveen/olg:tagname

      - name: Send Notification
        if: always()
        run: |
         echo "Build completed!\nVersion: '${{ github.run_number }}'\nDescription: ${{ github.event.inputs.build_description }}" | sendmail soumyanaveen1996@gmail.com
 
