name: OLG Application Pipeline

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Select build type'
        required: true
        default: 'dev_olg'
        options:
          - value: 'dev_frontm'
            description: 'Development build for Frontm'
          - value: 'dev_olg'
            description: 'Development build for OLG'
          - value: 'prod_frontm'
            description: 'Production build for Frontm'
          - value: 'prod_olg'
            description: 'Production build for OLG'
